version: '3'
services:
  php:
    container_name: metro-guestbook_php
    build: ./docker/php
    environment:
      PHP_IDE_CONFIG: "serverName=docker"
      XDEBUG_CONFIG: "idekey=PHPSTORM"
    volumes:
      - .:/var/application/metro-guestbook
      - ./docker/php/php.ini:/usr/local/etc/php/php.ini
    links:
      - mariadb
      - redis

  mariadb:
    container_name: metro-guestbook_mariadb
    image: mariadb:10
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: guestbook
    volumes:
      - ./docker/mariadb/initdb:/docker-entrypoint-initdb.d
      - ./docker/mariadb/data:/var/lib/mysql
    ports:
      - 3306:3306

  redis:
    container_name: metro-guestbook_redis
    image: redis:5
    ports:
      - 6379:6379


  nginx:
    container_name: metro-guestbook_challenge_nginx
    build: docker/nginx
    ports:
      - "8001:80"
    links:
      - php
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - .:/var/application/metro-guestbook


